#!/bin/bash
#/etc/init.d/rtsp_viewer

### BEGIN INIT INFO
# Provides:          rtsp_viewer
# Required-Start:    $network $syslog $remote_fs
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RTSP Viewier
# Description:       Turns a Raspbery Pi into a RTSP Viewer for multiple feeds.
### END INIT INFO

#cd /etc/init.d && sudo wget https://raw.githubusercontent.com/maddog986/raspberry_pi_rtsp/master/rtsp_viewer -O rtsp_viewer && sudo chmod +x ./rtsp_viewer && sudo ./rtsp_viewer install

# Start displaying camera feeds
case "$1" in
    start|repair)
        #loads file that has the feeds
        readarray cameras < /home/pi/rtsp_viewer.txt

        if [ "$1" = "start" ]; then
            killall omxplayer screen
        fi

        # monitor size, doesnt work right yet
        width=$(tvservice -s | grep -Po "([0-9]{3,4}x[0-9]{3,4})" | cut -d'x' -f1)
        height=$(tvservice -s | grep -Po "([0-9]{3,4}x[0-9]{3,4})" | cut -d'x' -f2)
        #width=1920
        #height=1080

        totalcameras=${#cameras[@]}
        echo Total Cameras: $totalcameras

        if (( $totalcameras % 2 )); then
            (( totalcameras += 1 ))
        fi

        if [ "${#cameras[@]}" -eq 1 ]; then
            perrow=1
            totalcameras=1;
        elif [ "$totalcameras" -eq 2 ]; then perrow=2;
        elif [ "$totalcameras" -eq 4 ]; then perrow=2;
        elif [ "$totalcameras" -eq 6 ]; then perrow=3;
        elif [ "$totalcameras" -ge 8 ]; then perrow=3;
        fi

        echo Per Row: $perrow
        totalrows=$((($totalcameras+$perrow-1)/$perrow))

        echo Total Rows: $totalrows

        columns=$((($totalcameras+$totalrows-1)/$totalrows))
        echo Columns: $columns

        (( counter = 1 ))
        (( x = 0 ))
        (( y = 0 ))
        (( row = 1 ))
        (( w = width / columns )) #width of each camera will be based on how many per row
        (( h = height / totalrows ))
        (( x2 = w )) #width of the camera box
        (( y2 = h )) #height of the camera box

        echo Starting Cameras

        for i in "${cameras[@]}"
        do
            name='Camera_'$counter

            #if camera not already playing, run the command
            if (!(screen -list | grep -q $name)) then
                if [[ $i != "" ]]; then
                    command="screen -dmS $name sh -c 'omxplayer --avdict rtsp_transport:tcp --win $x,$y,$x2,$y2 $i --live -n -1'"
                    echo $name Loading: $command
                    eval $command
                fi
            fi

            if (( $counter % $columns == 0 )); then
                (( row += 1 )) #increase row
                (( x = 0 )) #reset next camera to left position
                (( y += h )) #set new y value
                (( x2 = w )) #end width position of next camera box
                (( y2 += h )) #end height positon of next camera box
            else
                (( x += w )) #move camera over one spot
                (( x2 += w )) #move camera over one spot
            fi

            (( counter += 1 )) #camera loaded count
        done
    ;;

    # Stop displaying camera feeds
    stop)
        killall omxplayer.bin
        echo "Camera Display Ended"
    ;;

    # Update self
    update)
        # Stop script
        /etc/init.d/rtsp_viewer stop

        # Update script
        wget https://raw.githubusercontent.com/maddog986/raspberry_pi_rtsp/master/rtsp_viewer -O /etc/init.d/rtsp_viewer

        # Start it up again
        /etc/init.d/rtsp_viewer start
    ;;

    install)
        # Update && Upgrade the Package Manager Sources
        apt-get -y update
        
        # Setup a cron job file
        echo "# m h dom mon dow user  command
* * * * * root sudo /etc/init.d/rtsp_viewer repair
0 5 * * * root sudo /etc/init.d/rtsp_viewer update
0 6 * * * root sudo reboot

" > /etc/cron.d/rtsp_viewer

        #create feeds file
        echo "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov" > /home/pi/rtsp_viewer.txt

        # Install the Packages
        if [ $(dpkg-query -W -f='${Status}' omxplayer 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
            apt-get install omxplayer -y
        fi

        # Install the Packages
        if [ $(dpkg-query -W -f='${Status}' screen 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
            apt-get install screen  -y
        fi

        # Auto start the cameras
        update-rc.d rtsp_viewer defaults

        # Reboot so changes take effect
        reboot
    ;;

    *)
        echo "Usage: /etc/init.d/rtsp_viewer {start|stop|repair|update}"
        exit 1
    ;;
esac

exit 0
